### ISSUE TITLE
testing code extensively

### ISSUE THREAD

**Issue by larsuzh** [uzh-ase-fs24/whami#62]
As a: Developer
I want: the application code to be automatically tested
So that: I can be sure I did not introduce unwanted changes or errors to maintain high code quality

- [x] uzh-ase-fs24/backend#40
- [x] uzh-ase-fs24/backend#43
- [x] uzh-ase-fs24/workspace#89
- [x] uzh-ase-fs24/frontend#54
